// The installer speaks like UwUMail's default, playful tone, in German or English.

const de = {
  brand: "UwUMail",
  welcomeTitle: "Hallo! Ich bin Nyu",
  welcomeBody: "Ich richte UwUMail in ein paar Sekunden auf deinem PC ein.",
  againTitle: "Schön, dich wiederzusehen!",
  againBody: "UwUMail {installed} ist schon da. Ich bringe es auf {version}, deine Mails bleiben, wo sie sind.",
  install: "Installieren",
  update: "Aktualisieren",
  reinstall: "Neu installieren",
  options: "Optionen",
  fewerOptions: "Weniger Optionen",
  folder: "Speicherort",
  change: "Ändern …",
  desktopShortcut: "Verknüpfung auf dem Desktop",
  autostart: "Mit Windows starten",
  autostartHint: "Startet leise im Infobereich neben der Uhr.",
  defaultMailApp: "Als Standard-Mail-App",
  defaultMailAppHint: "Mail-Links öffnen UwUMail. Windows fragt einmal nach.",
  runningTitle: "UwUMail ist gerade offen",
  runningBody: "Ich schließe es kurz, damit ich weitermachen kann. Deine Mails sind sicher.",
  closeAndContinue: "Schließen und weiter",
  back: "Zurück",
  progressInstall: "Nyu richtet alles ein …",
  progressUpdate: "Nyu bringt UwUMail auf den neuesten Stand …",
  progressUninstall: "Nyu räumt auf …",
  quotes: [
    "Faltet Umschläge …",
    "Sortiert Sternchen …",
    "Poliert den Posteingang …",
    "Wärmt die Tastatur vor …",
    "Übt Ohrenwackeln …",
    "Füllt die Tinte nach …",
    "Zählt die Herzchen …",
  ],
  doneTitle: "Fertig! ✧",
  doneBody: "UwUMail ist bereit für deine Mails.",
  updateDoneTitle: "Alles frisch! ✧",
  updateDoneBody: "UwUMail {version} startet gleich wieder.",
  tipsTitle: "Kleine Tipps",
  tips: [
    "Einfach oder Profi? Das Layout wechselst du jederzeit in den Einstellungen.",
    "Kann dein Server JMAP, kommen neue Mails sofort an.",
    "Lieber ohne Zwinkern? Stell den Ton auf „Neutral“.",
  ],
  defaultAppsHint: "Bestätige UwUMail noch in den Windows-Einstellungen, die gerade aufgegangen sind.",
  start: "UwUMail starten",
  close: "Schließen",
  errorTitle: "Hoppla, das hat nicht geklappt",
  retry: "Nochmal versuchen",
  uninstallTitle: "Schade, dass du gehst …",
  uninstallBody: "Ich entferne UwUMail von diesem PC.",
  keepData: "Mails und Einstellungen behalten",
  keepDataHint: "Praktisch, falls du wiederkommst. Sonst lösche ich auch gespeicherte Passwörter.",
  uninstall: "Deinstallieren",
  keep: "Doch behalten",
  goodbyeTitle: "Tschüss! (｡•́︿•̀｡)",
  goodbyeBody: "UwUMail ist entfernt. Komm gern wieder vorbei.",
  soundOn: "Ton an",
  soundOff: "Ton aus",
  minimize: "Minimieren",
  devBuild: "Entwicklungs-Build: UwUMail ist hier nicht mit drin.",
  sandbox: "Testmodus: Es wird nur in einem Testordner installiert.",
  footer: "Version {version} · Open Source",
};

const en: typeof de = {
  brand: "UwUMail",
  welcomeTitle: "Hi! I'm Nyu",
  welcomeBody: "I'll set up UwUMail on your PC in a few seconds.",
  againTitle: "Nice to see you again!",
  againBody: "UwUMail {installed} is already here. I'll bring it to {version}, and your mail stays where it is.",
  install: "Install",
  update: "Update",
  reinstall: "Reinstall",
  options: "Options",
  fewerOptions: "Fewer options",
  folder: "Location",
  change: "Change …",
  desktopShortcut: "Shortcut on the desktop",
  autostart: "Start with Windows",
  autostartHint: "Starts quietly in the notification area next to the clock.",
  defaultMailApp: "Default mail app",
  defaultMailAppHint: "Mail links open UwUMail. Windows asks once.",
  runningTitle: "UwUMail is open right now",
  runningBody: "I'll close it for a moment so I can carry on. Your mail is safe.",
  closeAndContinue: "Close and continue",
  back: "Back",
  progressInstall: "Nyu is setting everything up …",
  progressUpdate: "Nyu is bringing UwUMail up to date …",
  progressUninstall: "Nyu is tidying up …",
  quotes: [
    "Folding envelopes …",
    "Sorting little stars …",
    "Polishing the inbox …",
    "Warming up the keyboard …",
    "Practicing ear wiggles …",
    "Refilling the ink …",
    "Counting hearts …",
  ],
  doneTitle: "All done! ✧",
  doneBody: "UwUMail is ready for your mail.",
  updateDoneTitle: "All fresh! ✧",
  updateDoneBody: "UwUMail {version} starts again in a moment.",
  tipsTitle: "Little tips",
  tips: [
    "Simple or Pro? Switch the layout any time in the settings.",
    "If your server speaks JMAP, new mail arrives instantly.",
    "Rather without the winks? Set the tone to “Neutral”.",
  ],
  defaultAppsHint: "Please confirm UwUMail in the Windows settings that just opened.",
  start: "Start UwUMail",
  close: "Close",
  errorTitle: "Oops, that didn't work",
  retry: "Try again",
  uninstallTitle: "Sad to see you go …",
  uninstallBody: "I'll remove UwUMail from this PC.",
  keepData: "Keep mail and settings",
  keepDataHint: "Handy if you come back. Otherwise I also delete saved passwords.",
  uninstall: "Uninstall",
  keep: "Keep it",
  goodbyeTitle: "Bye! (｡•́︿•̀｡)",
  goodbyeBody: "UwUMail is removed. Come back any time.",
  soundOn: "Sound on",
  soundOff: "Sound off",
  minimize: "Minimize",
  devBuild: "Development build: UwUMail isn't packed inside.",
  sandbox: "Test mode: installs into a test folder only.",
  footer: "Version {version} · Open source",
};

export type Texts = typeof de;

export const texts: Texts = navigator.language.toLowerCase().startsWith("de") ? de : en;

export function fill(template: string, values: Record<string, string>) {
  return template.replace(/\{(\w+)\}/g, (_, key: string) => values[key] ?? "");
}
